id: smart.permission-tickets
canonical: http://smarthealthit.org/ig/permission-tickets
name: SmartPermissionTickets
title: "SMART Permission Tickets"
status: draft
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2024+
releaseLabel: ci-build

pages:
  index.md:
    title: Permission Ticket Architecture
  typescript-definitions.md:
    title: TypeScript Definitions
  oidf-issuers.md:
    title: OpenID Federation Issuers
  downloads.md:
    title: Downloads

menu:
  IG Home: index.html
  TypeScript Definitions: typescript-definitions.html
  OpenID Federation: oidf-issuers.html
  Downloads: downloads.html
  Artifacts: artifacts.html
