id: smart.permission-tickets
canonical: http://smarthealthit.org/ig/permission-tickets
name: SmartPermissionTickets
title: "SMART Permission Tickets"
status: draft
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2024+
releaseLabel: ci-build

pages:
  index.md:
    title: Permission Ticket Architecture
  use-case-catalog.md:
    title: Use Case Catalog
  typescript-definitions.md:
    title: TypeScript Definitions
  downloads.md:
    title: Downloads
  proposal-001-authz-code-fallback.md:
    title: "Proposal 001: Authz Code Fallback"
  proposal-002-oidf-issuers.md:
    title: "Proposal 002: OpenID Federation Issuers"
  proposal-003-smart-launch-issuance.md:
    title: "Proposal 003: SMART Launch Issuance"
  proposal-005-sensitive-data-modeling.md:
    title: "Proposal 005: Sensitive Data Profile"

menu:
  IG Home: index.html
  Use Case Catalog: use-case-catalog.html
  TypeScript Definitions: typescript-definitions.html
  Proposals:
    "001: Authz Code Fallback": proposal-001-authz-code-fallback.html
    "002: OpenID Federation Issuers": proposal-002-oidf-issuers.html
    "003: SMART Launch Issuance": proposal-003-smart-launch-issuance.html
    "005: Sensitive Data Profile": proposal-005-sensitive-data-modeling.html
  Downloads: downloads.html
  Artifacts: artifacts.html
