// Logical Model for the Permission Ticket
Logical: PermissionTicket
Title: "Permission Ticket (JWT Payload)"
Description: "The full payload of a Permission Ticket, including standard JWT claims and the custom ticket_context object."
* iss 1..1 string "Issuer (Trust Broker URL)"
* sub 1..1 string "Issuer-defined subject of the authorization grant (profile-specific). This value is issuer-local and SHALL NOT be relied on as a cross-party client identifier."
* aud 1..* uri "Audience (recipient URL(s) or network / trust framework identifier)"
* exp 1..1 integer "Expiration Timestamp"
* iat 0..1 integer "Issued-At Timestamp"
* jti 0..1 string "Unique Ticket ID"
* ticket_type 1..1 uri "Ticket type URI identifying the ticket schema and processing rules"
* cnf 1..1 BackboneElement "Confirmation (RFC 7800)"
  * jkt 1..1 string "JWK Thumbprint (RFC 7638) of the authorized client key"
* revocation 0..1 BackboneElement "Revocation Information"
  * url 1..1 url "URL of the Credential Revocation List (CRL)"
  * rid 1..1 string "Revocation Identifier (opaque, max 24 chars)"
* ticket_context 1..1 BackboneElement "Permission Details"
  * subject 1..1 BackboneElement "The Patient or Subject of the data"
    * type 1..1 code "Subject resolution mode: match | identifier | reference"
    * traits 0..1 Patient "Demographic traits for matching (type=match)"
    * resourceType 0..1 string "Resource Type (e.g. Patient)"
    * id 0..1 string "Local resource ID (type=reference)"
    * reference 0..1 string "Local resource reference, e.g. Patient/123 (type=reference)"
    * identifier 0..* Identifier "Business Identifier (type=identifier)"
  * actor 0..1 BackboneElement "The Requesting Agent"
    * resourceType 1..1 string "Type of actor (Practitioner, PractitionerRole, RelatedPerson, Organization)"
    * name 0..* HumanName "Name of the actor"
    * telecom 0..* ContactPoint "Contact details"
    * identifier 0..* Identifier "Actor identifiers (NPI, etc)"
    * relationship 0..* CodeableConcept "Relationship to subject"
    * type 0..* CodeableConcept "Organization type"
    * contained 0..* Resource "Embedded resources"
  * context 0..1 BackboneElement "The Trigger Event"
    * type 1..1 Coding "Type of context (e.g. ActReason)"
    * focus 0..1 Coding "Clinical Focus (e.g. Condition)"
    * identifier 0..* Identifier "Issuer-specific identifiers (Case ID, etc)"
  * capability 1..1 BackboneElement "Access Capabilities"
    * scopes 0..* string "SMART Scopes (e.g. patient/Immunization.rs)"
    * periods 0..* Period "Time restrictions (Service Date)"
    * jurisdictions 0..* Address "Jurisdictional restrictions (state/country granularity)"
    * organizations 0..* Organization "Source organization restrictions (matching by identifier preferred)"
