// Logical Model for the Permission Ticket (Simplified Ticket Model)
// NOTE: This FSH logical model is a best-effort structural overview.
// The authoritative source for conditional cardinality, per-ticket-type context
// rules, and cross-field invariants is the specification prose and shared Zod schema.
Logical: PermissionTicket
Title: "Permission Ticket (JWT Payload)"
Description: "Portable kernel of a Permission Ticket. Includes the JWT security envelope, subject identification, optional requester, access grant semantics, ticket-type-specific context, optional presenter binding, optional revocation, and optional must-understand extensibility."
* iss 1..1 string "Issuer URL"
* aud 1..* uri "Coarse intended Data Holder audience (specific Data Holder URL(s) or trust framework identifier). Arrays SHALL be homogeneous."
* aud_type 0..1 code "Optional interpretation of aud: data_holder_url | trust_framework. Applies uniformly to the singleton or every entry in the aud array."
* exp 1..1 integer "Expiration Timestamp"
* iat 0..1 integer "Issued-At Timestamp"
* jti 1..1 string "Unique Ticket ID"
* ticket_type 1..1 uri "Ticket type URI identifying the ticket schema and processing rules"
* presenter_binding 0..1 BackboneElement "Optional presenter binding. Exactly one method applies when present."
  * method 1..1 code "Binding method: jkt | framework_client"
  * jkt 0..1 string "JWK Thumbprint (RFC 7638) when method=jkt"
  * framework 0..1 uri "Framework instance URI when method=framework_client"
  * framework_type 0..1 code "Framework family: well-known | udap"
  * entity_uri 0..1 uri "Framework-recognized client entity URI"
* revocation 0..1 BackboneElement "Optional revocation information"
  * url 1..1 url "URL of the issuer's status list"
  * index 1..1 integer "Zero-based bit position assigned to this ticket"
* must_understand 0..* string "Payload claim names the Data Holder MUST understand beyond the base kernel. Top-level claims only."
* subject 1..1 BackboneElement "Subject whose data may be accessed"
  * patient 1..1 Patient "Inline patient facts for Data Holder-side resolution. May be thin."
  * recipient_record 0..1 Reference "Optional Data Holder-local patient locator"
* requester 0..1 Resource "Issuer-attested real-world party for whom the grant exists. Typical types: RelatedPerson, Practitioner, PractitionerRole, Organization."
* access 1..1 BackboneElement "Normative authorization model"
  * permissions 1..* BackboneElement "One or more permission rules. When kind=data: resource_type and interactions are required (interactions must be non-empty). When kind=operation: name is required."
    * kind 1..1 code "Permission kind: data | operation"
    * resource_type 0..1 string "FHIR resource type (or * for broad access). Required when kind=data."
    * interactions 0..* code "REST interactions: read | search | history | create | update | patch | delete. Required and non-empty when kind=data."
    * category_any_of 0..* Coding "Category filter group (OR within group). Only when kind=data."
    * code_any_of 0..* Coding "Code filter group (OR within group). Only when kind=data."
    * name 0..1 string "Operation name when kind=operation. Required when kind=operation."
    * target 0..1 Reference "Operation target. Only when kind=operation."
  * data_period 0..1 Period "One coarse timeframe. Mint separate tickets for disjoint windows."
  * data_holder_filter 0..* BackboneElement "Optional Data Holder scoping. Entries are ORed."
    * kind 1..1 code "Filter kind: jurisdiction | organization"
    * address 0..1 Address "Jurisdiction restriction when kind=jurisdiction"
    * organization 0..1 Organization "Organization restriction when kind=organization"
  * sensitive_data 0..1 code "exclude | include. If absent, the Data Holder applies its own default policy."
* context 0..1 BackboneElement "Ticket-type-specific required workflow semantics. For ticket types with no context fields, this may be omitted or empty."
  * reportable_condition 0..1 CodeableConcept "Public health: reportable condition"
  * concern 0..1 CodeableConcept "Social care: concern being addressed"
  * referral 0..1 Resource "Social care: referral ServiceRequest"
  * service 0..1 CodeableConcept "Payer claims: service being adjudicated"
  * claim 0..1 Resource "Payer claims: Claim artifact"
  * study 0..1 Resource "Research: ResearchStudy artifact"
  * reason 0..1 CodeableConcept "Provider consult: reason for consult"
  * consult_request 0..1 Resource "Provider consult: ServiceRequest"
